// UI Types
export const CLOSE_EVENT_MODAL = "CLOSE_EVENT_MODAL",
  CLOSE_ALERT = "CLOSE_ALERT",
  DISPATCH_NEW_EVENT_MODAL = "OPEN_NEW_EVENT_MODAL",
  DISPATCH_NEW_ALERT = "DISPATCH_NEW_ALERT",
  TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

// Event Data Types
export const DISPATCH_NEW_EVENTS = "DISPATCH_NEW_EVENTS";

// Search Param Types
export const DISPATCH_SELECTED_RADIUS = "DISPATCH_SELECTED_RADIUS",
  DISPATCH_SELECTED_DATE_RANGE = "DISPATCH_SELECTED_DATE_RANGE",
  DISPATCH_USER_COORDINATES = "DISPATCH_USER_COORDINATES",
  DISPATCH_MAP_ZOOM = "DISPATCH_MAP_ZOOM";

// Loading Types
export const REQUEST_LOCATION_PENDING = "REQUEST_LOCATION_PENDING",
  REQUEST_LOCATION_COMPLETE = "REQUEST_LOCATION_COMPLETE",
  REQUEST_EVENTS_PENDING = "REQUEST_EVENTS_PENDING",
  REQUEST_EVENTS_COMPLETE = "REQUEST_EVENTS_COMPLETE",
  REQUEST_RADIUS_UPDATE_PENDING = "REQUEST_RADIUS_UPDATE_PENDING",
  REQUEST_RADIUS_UPDATE_COMPLETE = "REQUEST_RADIUS_UPDATE_COMPLETE";
